# Site settings
title: Valentin Shuvaev
description: Valentin Shuvaev
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Valentin Shuvaev
user_description: Hello, my name is Valentin. I am a data scientist with a strong statistical background and hands-on experience in the implementation of ML algorithms (mainly Natural Language Processing algorithms).
user_title: Data Engineer
email: vshuvaevv@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
