# Site settings
title: Valentin Shuvaev
description: Valentin Shuvaev
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Valentin Shuvaev
user_description: I am an engineer with a strong statistical background and hands-on experience in API development. Most of my projects are related to data engineering (microservice development, ETL processes implementation, data pipeline maintenance). In addition, I have experience in the development and implementation of ML algorithms.
user_title: Data Engineer
email: vshuvaevv@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
